/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // 微信风格色彩
        wechat: {
          green: '#07C160',
          'green-dark': '#06AD56',
          bg: '#EDEDED',
          'bg-dark': '#111111',
          'chat-bg': '#F5F5F5',
          'bubble-self': '#95EC69',
          'bubble-other': '#FFFFFF',
        },
        // 现代深色主题
        dark: {
          950: '#06060a',
          900: '#0A0A0F',
          800: '#12121A',
          700: '#1A1A25',
          600: '#252530',
          500: '#35354A',
          400: '#4A4A65',
        },
        accent: {
          primary: '#6366F1',
          secondary: '#8B5CF6',
          success: '#10B981',
          warning: '#F59E0B',
          error: '#EF4444',
        },
        // Stitch 设计稿 Material Design 3 色板
        'primary': '#bdc2ff',
        'primary-dim': '#acb3ff',
        'primary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#ced1ff',
        'primary-container': '#2f3aa3',
        'on-primary': '#28329c',
        'on-primary-fixed': '#27319b',
        'on-primary-fixed-variant': '#4650b9',
        'on-primary-container': '#c9cdff',
        'secondary': '#909fb5',
        'secondary-dim': '#909fb5',
        'secondary-fixed': '#d5e3fc',
        'secondary-fixed-dim': '#c7d5ed',
        'secondary-container': '#2e3c4f',
        'on-secondary': '#122133',
        'on-secondary-fixed': '#324053',
        'on-secondary-fixed-variant': '#4e5c71',
        'on-secondary-container': '#b2c0d8',
        'tertiary': '#c180ff',
        'tertiary-dim': '#9c48ea',
        'tertiary-fixed': '#af5cfe',
        'tertiary-fixed-dim': '#a14ef0',
        'tertiary-container': '#af5cfe',
        'on-tertiary': '#33005b',
        'on-tertiary-fixed': '#000000',
        'on-tertiary-fixed-variant': '#16002c',
        'on-tertiary-container': '#000000',
        'error': '#ec7c8a',
        'error-dim': '#b95463',
        'error-container': '#7f2737',
        'on-error': '#490013',
        'on-error-container': '#ff97a3',
        'surface': '#060e20',
        'surface-dim': '#060e20',
        'surface-bright': '#002867',
        'surface-variant': '#00225a',
        'surface-tint': '#bdc2ff',
        'surface-container': '#05183c',
        'surface-container-low': '#06122d',
        'surface-container-high': '#031d4b',
        'surface-container-highest': '#00225a',
        'surface-container-lowest': '#000000',
        'on-surface': '#dee5ff',
        'on-surface-variant': '#91aaeb',
        'inverse-surface': '#faf8ff',
        'inverse-on-surface': '#4d556b',
        'inverse-primary': '#4954bc',
        'outline': '#5b74b1',
        'outline-variant': '#2b4680',
        'background': '#060e20',
        'on-background': '#dee5ff',
      },
      fontFamily: {
        sans: ['Geist', 'SF Pro Display', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
}
