export type SessionMode = 'upload' | 'topic' | 'review'
export type SessionStatus = 'active' | 'completed' | 'reviewing' | 'archived'

export interface MasteryAssessment {
  score: number
  level_label: string
  strengths: string[]
  weak_areas: string[]
}

export interface AIMessageMetadata {
  step_transition?: number
  session_complete?: boolean
  mastery_level?: number | null
  mastery_assessment?: MasteryAssessment | null
  recall_round?: number
  recall_passed?: boolean
  schedule_cards?: Array<{
    cue: string
    expectedAnswer: string
    sourceQuote?: string
  }>
  clean_text?: string
}

export interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
  step: number
  content_type: string
  metadata: AIMessageMetadata | null
  created_at: string
}

export interface SessionData {
  id: string
  title: string
  mode: SessionMode
  source_material: string
  current_step: number
  status: SessionStatus
  content_type?: string
  mastery_level?: number | null
  mastery_assessment?: MasteryAssessment | null
}

export interface SessionDetail extends SessionData {
  messages: Message[]
}

export interface SessionSummary {
  id: string
  title: string
  mode: SessionMode
  current_step: number
  status: SessionStatus
  review_source_id?: string | null
  next_review?: string | null
  review_count?: number
  created_at: string
  updated_at: string
}

export interface LocationState {
  returnTo?: string
  initialMessage?: string
}

export type AgentMode = 'general' | 'deep'

export interface AgentConversation {
  id: string
  title: string
  mode: AgentMode
  status: string
  created_at: string
  updated_at: string
}

export interface AgentConversationDetail extends AgentConversation {
  messages: Message[]
}

export interface PrdFeature {
  id: string
  name: string
  description: string
  acceptanceCriteria: string[]
}

export interface TestUnit {
  id: string
  featureId: string
  name: string
  description: string
}

export interface TestCaseItem {
  caseId: string
  title: string
  module: string
  priority: 'P0' | 'P1' | 'P2'
  precondition: string
  steps: string[]
  expected: string
  relatedBug: string
  testType: string
  source: string
}

export interface HumanReviewItem {
  id: string
  confidence: 'HIGH' | 'MEDIUM' | 'LOW'
  dimension: string
  description: string
  suggestion: string
}

export interface PrdWorkflowResult {
  title: string
  mode: 'LITE' | 'STANDARD' | 'FULL'
  parsedPrd: {
    title: string
    wordCount: number
    features: PrdFeature[]
    constraints: string[]
    acceptanceCriteria: string[]
  }
  testUnits: TestUnit[]
  testcases: TestCaseItem[]
  reviewReport: {
    total: number
    highConfidencePass: number
    needHumanReview: number
    flaggedGaps: number
    findings: string[]
    coverage: {
      featureTotal: number
      featureCovered: number
      featureCoverageText: string
      bugTotal: number
      bugCovered: number
      bugCoverageText: string
      boundaryAutoGenerated: number
    }
    needHumanReviewItems: HumanReviewItem[]
    needSupplement: boolean
  }
  markdown: string
}
