import { useCallback, useEffect, useState } from 'react'
import { CalendarPlus, Check, Pencil, Plus, Send, Sparkles, Trash2 } from 'lucide-react'
import Modal from '../../components/Modal'
import { useAuth } from '../../contexts/AuthContext'
import { useBusinessApi } from '../../lib/businessApi'
import { jsonRequest } from '../../lib/http'
import { campaignPath } from './api'
import { ActionState, RefreshButton, SectionHeading, ViewTabs, iconButton, inputClass, primaryButton, secondaryButton, textareaClass } from './ui'

type DistributionTab = 'calendar' | 'platform'
const tabs = [{ id: 'calendar' as const, label: '内容日历' }, { id: 'platform' as const, label: '五平台适配' }]

export default function DistributionView() {
  const [tab, setTab] = useState<DistributionTab>('calendar')
  return <section aria-label="内容分发计划"><ViewTabs items={tabs} value={tab} onChange={setTab} label="分发计划视图" />{tab === 'calendar' ? <CalendarPanel /> : <PlatformPanel />}</section>
}

interface CalendarEvent { id: string; title: string; scheduled_date: string; scheduled_time?: string | null; content_type: string; platform: string[]; status: string; priority: number; hotspot_tag?: string | null; description?: string }
interface Hotspot { name: string; month: number; day: number; icon: string; category: string; is_major: boolean }

function CalendarPanel() {
  const request = useBusinessApi(); const { activeTenant } = useAuth(); const now = new Date()
  const [year, setYear] = useState(now.getFullYear()); const [month, setMonth] = useState(now.getMonth() + 1)
  const [events, setEvents] = useState<CalendarEvent[]>([]); const [hotspots, setHotspots] = useState<Hotspot[]>([])
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [date, setDate] = useState(`${year}-${String(month).padStart(2, '0')}-01`); const [time, setTime] = useState('20:00'); const [platforms, setPlatforms] = useState<string[]>(['xiaohongshu']); const [contentType, setContentType] = useState('grass')
  const [planOpen, setPlanOpen] = useState(false); const [brand, setBrand] = useState(''); const [industry, setIndustry] = useState('电商零售')
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [eventResponse, hotspotResponse] = await Promise.all([request<{ events: CalendarEvent[] }>(campaignPath(`/calendar/events?year=${year}&month=${month}`)), request<{ hotspots: Hotspot[] }>(campaignPath(`/calendar/hotspots?month=${month}`))]); setEvents(eventResponse.events); setHotspots(hotspotResponse.hotspots) } catch (reason) { setError(reason instanceof Error ? reason.message : '日历加载失败') } finally { setLoading(false) } }, [month, request, year])
  useEffect(() => { setDate(`${year}-${String(month).padStart(2, '0')}-01`); void load() }, [activeTenant?.id, load, month, year])
  async function create() { try { await request(campaignPath('/calendar/events'), jsonRequest('POST', { title: title.trim(), scheduled_date: date, scheduled_time: time || null, content_type: contentType, platform: platforms, priority: 3 })); setOpen(false); setTitle(''); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : '日历条目创建失败') } }
  async function eventAction(event: CalendarEvent, action: 'publish' | 'create' | 'delete') { setSuccess(''); try { if (action === 'delete') await request(campaignPath(`/calendar/events/${event.id}`), jsonRequest('DELETE')); else if (action === 'publish') await request(campaignPath(`/calendar/events/${event.id}`), jsonRequest('PUT', { status: 'published' })); else { const prepared = await request<{ workflow_params: { topic_direction: string } }>(campaignPath(`/calendar/events/${event.id}/create-content`), jsonRequest('POST')); const workflow = await request<{ thread_id: string }>(campaignPath('/workflow/start'), jsonRequest('POST', prepared.workflow_params)); setSuccess(`已创建工作流 ${workflow.thread_id.slice(-8)}`) } await load() } catch (reason) { setError(reason instanceof Error ? reason.message : '日历操作失败') } }
  async function generatePlan() { setLoading(true); setError(''); try { const result = await request<{ total: number }>(campaignPath('/calendar/generate-plan'), jsonRequest('POST', { brand_description: brand.trim(), industry: industry.trim(), year, month })); setSuccess(`已生成 ${result.total} 条内容计划`); setPlanOpen(false); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'AI 排期失败') } finally { setLoading(false) } }
  const platformOptions = ['xiaohongshu', 'douyin', 'wechat', 'bilibili', 'weibo']
  return <div><SectionHeading title={`${year} 年 ${month} 月内容排期`} action={<div className="flex gap-1"><RefreshButton onClick={() => void load()} /><button onClick={() => setOpen(true)} className={iconButton} title="新建日历条目" aria-label="新建日历条目"><Plus size={15} /></button></div>} /><div className="mt-4 flex flex-wrap gap-2 border-y border-border py-3"><select value={year} onChange={event => setYear(Number(event.target.value))} className="h-9 rounded-md border border-border bg-page px-3 text-xs">{[2025, 2026, 2027, 2028, 2029, 2030].map(value => <option key={value}>{value}</option>)}</select><select value={month} onChange={event => setMonth(Number(event.target.value))} className="h-9 rounded-md border border-border bg-page px-3 text-xs">{Array.from({ length: 12 }, (_, index) => index + 1).map(value => <option key={value}>{value} 月</option>)}</select><button onClick={() => setPlanOpen(true)} className={secondaryButton}><Sparkles size={13} /> AI 排期</button><div className="ml-auto flex flex-wrap items-center gap-2 text-[10px] text-text-tertiary">{hotspots.filter(item => item.is_major).slice(0, 4).map(item => <span key={item.name}>{item.month}/{item.day} {item.name}</span>)}</div></div><div className="mt-4"><ActionState loading={loading} error={error} success={success} /></div><div className="mt-4 divide-y divide-border border-y border-border">{events.length === 0 && !loading ? <div className="py-12 text-center text-xs text-text-tertiary">本月暂无内容安排</div> : [...events].sort((a, b) => a.scheduled_date.localeCompare(b.scheduled_date)).map(event => <div key={event.id} className="grid grid-cols-[76px_minmax(0,1fr)_auto] items-center gap-4 py-4"><div className="font-mono text-xs text-text-tertiary">{event.scheduled_date.slice(5)}<div className="mt-1">{event.scheduled_time || '--:--'}</div></div><div className="min-w-0"><div className="flex items-center gap-2"><span className="truncate text-sm text-text">{event.title}</span><span className={`text-[10px] ${event.status === 'published' ? 'text-success' : 'text-text-tertiary'}`}>{event.status}</span></div><div className="mt-1 truncate text-[11px] text-text-tertiary">{event.content_type} · {event.platform.join(' / ')} {event.hotspot_tag ? `· ${event.hotspot_tag}` : ''}</div></div><div className="flex"><button onClick={() => void eventAction(event, 'create')} className={iconButton} title="进入创作工作流" aria-label="进入创作工作流"><CalendarPlus size={13} /></button>{event.status !== 'published' && <button onClick={() => void eventAction(event, 'publish')} className={iconButton} title="标记发布" aria-label="标记发布"><Check size={13} /></button>}<button onClick={() => void eventAction(event, 'delete')} className={`${iconButton} hover:text-danger`} title="删除" aria-label="删除"><Trash2 size={13} /></button></div></div>)}</div>
    <Modal open={open} onClose={() => setOpen(false)} title="新建内容日历条目"><div className="space-y-4"><label className="block text-xs text-text-secondary">内容标题<input value={title} onChange={event => setTitle(event.target.value)} className={inputClass} autoFocus /></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs text-text-secondary">日期<input type="date" value={date} onChange={event => setDate(event.target.value)} className={inputClass} /></label><label className="block text-xs text-text-secondary">时间<input type="time" value={time} onChange={event => setTime(event.target.value)} className={inputClass} /></label></div><label className="block text-xs text-text-secondary">内容类型<select value={contentType} onChange={event => setContentType(event.target.value)} className={inputClass}><option value="education">教育干货</option><option value="grass">种草推荐</option><option value="interaction">互动话题</option><option value="brand_story">品牌故事</option></select></label><div><span className="text-xs text-text-secondary">目标平台</span><div className="mt-2 flex flex-wrap gap-2">{platformOptions.map(value => <button key={value} onClick={() => setPlatforms(current => current.includes(value) ? current.filter(item => item !== value) : [...current, value])} className={`h-8 rounded-md border px-2 text-xs ${platforms.includes(value) ? 'border-text bg-accent text-page' : 'border-border text-text-secondary'}`}>{value}</button>)}</div></div><button onClick={() => void create()} disabled={!title.trim() || !date || !platforms.length} className={`${primaryButton} w-full`}>保存日历条目</button></div></Modal>
    <Modal open={planOpen} onClose={() => setPlanOpen(false)} title="AI 月度排期"><div className="space-y-4"><label className="block text-xs text-text-secondary">品牌与账号定位<textarea value={brand} onChange={event => setBrand(event.target.value)} className={textareaClass} autoFocus /></label><label className="block text-xs text-text-secondary">行业<input value={industry} onChange={event => setIndustry(event.target.value)} className={inputClass} /></label><button onClick={() => void generatePlan()} disabled={brand.trim().length < 5 || !industry.trim() || loading} className={`${primaryButton} w-full`}><Sparkles size={14} /> 生成 {year} 年 {month} 月排期</button></div></Modal>
  </div>
}

interface PlatformRule { id: string; name: string; max_words?: number; recommended_ratio?: string }
interface Variant { id: string; platform: string; suggested_title?: string | null; adapted_content: string; suggested_tags: string[]; word_count: number; is_edited: boolean; created_at?: string }

function PlatformPanel() {
  const request = useBusinessApi(); const { activeTenant } = useAuth(); const [rules, setRules] = useState<PlatformRule[]>([]); const [variants, setVariants] = useState<Variant[]>([])
  const [title, setTitle] = useState(''); const [article, setArticle] = useState(''); const [selected, setSelected] = useState<string[]>(['xiaohongshu', 'douyin', 'wechat', 'bilibili', 'weibo'])
  const [editing, setEditing] = useState<Variant | null>(null); const [editTitle, setEditTitle] = useState(''); const [editContent, setEditContent] = useState(''); const [editTags, setEditTags] = useState('')
  const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [ruleResponse, variantResponse] = await Promise.all([request<{ platforms: PlatformRule[] }>(campaignPath('/platform/rules')), request<{ items?: Variant[]; variants?: Variant[] }>(campaignPath('/platform/variants?page_size=50'))]); setRules(ruleResponse.platforms); setVariants(variantResponse.items || variantResponse.variants || []) } catch (reason) { setError(reason instanceof Error ? reason.message : '平台版本加载失败') } finally { setLoading(false) } }, [request])
  useEffect(() => { void load() }, [activeTenant?.id, load])
  async function adapt() { setLoading(true); setError(''); try { await request(campaignPath('/platform/adapt-all'), jsonRequest('POST', { source_title: title.trim() || null, source_article: article.trim(), platform_ids: selected })); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : '平台适配失败') } finally { setLoading(false) } }
  async function remove(id: string) { try { await request(campaignPath(`/platform/variant/${id}`), jsonRequest('DELETE')); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : '版本删除失败') } }
  function openEdit(item: Variant) { setEditing(item); setEditTitle(item.suggested_title || ''); setEditContent(item.adapted_content); setEditTags(item.suggested_tags.join(',')) }
  async function saveEdit() { if (!editing) return; try { await request(campaignPath(`/platform/variant/${editing.id}`), jsonRequest('PUT', { suggested_title: editTitle, adapted_content: editContent, suggested_tags: editTags.split(',').map(value => value.trim()).filter(Boolean) })); setEditing(null); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : '版本保存失败') } }
  return <div><SectionHeading title="五平台内容适配" action={<RefreshButton onClick={() => void load()} />} /><div className="mt-5 grid gap-5 border-y border-border py-5 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-4"><label className="block text-xs text-text-secondary">原文标题<input value={title} onChange={event => setTitle(event.target.value)} className={inputClass} /></label><label className="block text-xs text-text-secondary">原始内容<textarea value={article} onChange={event => setArticle(event.target.value)} className={`${textareaClass} min-h-56`} /></label></div><div><div className="text-xs text-text-secondary">目标平台</div><div className="mt-2 divide-y divide-border border-y border-border">{rules.map(rule => <label key={rule.id} className="flex items-center gap-3 py-3 text-xs text-text-secondary"><input type="checkbox" checked={selected.includes(rule.id)} onChange={() => setSelected(current => current.includes(rule.id) ? current.filter(item => item !== rule.id) : [...current, rule.id])} /><span className="flex-1 text-text">{rule.name}</span><span>{rule.recommended_ratio}</span></label>)}</div><button onClick={() => void adapt()} disabled={article.trim().length < 10 || !selected.length || loading} className={`${primaryButton} mt-4 w-full`}><Sparkles size={14} /> 生成平台版本</button></div></div><div className="mt-4"><ActionState loading={loading} error={error} /></div><div className="mt-5 grid gap-4 md:grid-cols-2">{variants.map(item => <article key={item.id} className="rounded-md border border-border p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-medium text-text">{rules.find(rule => rule.id === item.platform)?.name || item.platform}</span><span className="ml-2 text-[10px] text-text-tertiary">{item.word_count} 字{item.is_edited ? ' · 已编辑' : ''}</span></div><div className="flex"><button onClick={() => openEdit(item)} className={iconButton} title="编辑版本" aria-label="编辑版本"><Pencil size={13} /></button><button onClick={() => void remove(item.id)} className={`${iconButton} hover:text-danger`} title="删除版本" aria-label="删除版本"><Trash2 size={13} /></button></div></div><h3 className="mt-3 text-sm text-text">{item.suggested_title || '未生成标题'}</h3><p className="mt-2 line-clamp-6 whitespace-pre-wrap text-xs leading-5 text-text-secondary">{item.adapted_content}</p><div className="mt-3 flex flex-wrap gap-1 text-[10px] text-text-tertiary">{item.suggested_tags.map(tag => <span key={tag}>#{tag}</span>)}</div></article>)}</div>
    <Modal open={Boolean(editing)} onClose={() => setEditing(null)} title="编辑平台版本"><div className="space-y-4"><label className="block text-xs text-text-secondary">标题<input value={editTitle} onChange={event => setEditTitle(event.target.value)} className={inputClass} /></label><label className="block text-xs text-text-secondary">内容<textarea value={editContent} onChange={event => setEditContent(event.target.value)} className={`${textareaClass} min-h-64`} /></label><label className="block text-xs text-text-secondary">标签<input value={editTags} onChange={event => setEditTags(event.target.value)} className={inputClass} /></label><button onClick={() => void saveEdit()} className={`${primaryButton} w-full`}><Send size={13} /> 保存版本</button></div></Modal>
  </div>
}
