import { useCallback, useEffect, useMemo, useState } from 'react'
import { Download, Eye, Film, Play, RefreshCw, Trash2 } from 'lucide-react'
import { useAuth } from '../../contexts/AuthContext'
import { useBusinessApi, useBusinessBlobApi } from '../../lib/businessApi'
import { jsonRequest } from '../../lib/http'
import { campaignPath } from './api'
import { ActionState, SectionHeading, iconButton, inputClass, primaryButton, secondaryButton, textareaClass } from './ui'

interface VoiceOption { label: string; value: string; gender: string; description: string }
interface VideoTask { id: string; title?: string | null; topic: string; status: string; video_url?: string | null; error_message?: string | null; script_json?: Record<string, unknown> | null; created_at?: string | null }

export default function VideoProductionView() {
  const request = useBusinessApi(); const requestBlob = useBusinessBlobApi(); const { activeTenant } = useAuth()
  const [tasks, setTasks] = useState<VideoTask[]>([]); const [voices, setVoices] = useState<VoiceOption[]>([]); const [activeId, setActiveId] = useState('')
  const [topic, setTopic] = useState(''); const [style, setStyle] = useState('专业、简洁'); const [voice, setVoice] = useState(''); const [template, setTemplate] = useState('KnowledgeVideo'); const [ratio, setRatio] = useState('9:16')
  const [preview, setPreview] = useState<Record<string, unknown> | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setError(''); try { const [taskResponse, voiceResponse] = await Promise.all([request<{ videos: VideoTask[] }>(campaignPath('/video/list?limit=50')), request<VoiceOption[]>(campaignPath('/video/voices'))]); setTasks(taskResponse.videos); setVoices(voiceResponse); setVoice(current => current || voiceResponse[0]?.value || ''); setActiveId(current => current || taskResponse.videos[0]?.id || '') } catch (reason) { setError(reason instanceof Error ? reason.message : '视频任务加载失败') } }, [request])
  useEffect(() => { setTasks([]); setActiveId(''); void load() }, [activeTenant?.id, load])
  const activeTask = useMemo(() => tasks.find(task => task.id === activeId), [activeId, tasks])
  useEffect(() => {
    if (!tasks.some(task => !['completed', 'failed'].includes(task.status))) return
    const timer = window.setInterval(async () => {
      const pending = tasks.filter(task => !['completed', 'failed'].includes(task.status))
      const statuses = await Promise.all(pending.map(task => request<VideoTask>(campaignPath(`/video/status/${task.id}`)).catch(() => task)))
      setTasks(current => current.map(task => statuses.find(status => status.id === task.id) || task))
    }, 2500)
    return () => window.clearInterval(timer)
  }, [request, tasks])
  async function previewScript() { if (!topic.trim()) return; setLoading(true); setError(''); try { const result = await request<{ script: Record<string, unknown> }>(campaignPath('/video/script/preview'), jsonRequest('POST', { topic: topic.trim(), style, template })); setPreview(result.script) } catch (reason) { setError(reason instanceof Error ? reason.message : '脚本预览失败') } finally { setLoading(false) } }
  async function generate() { if (!topic.trim()) return; setLoading(true); setError(''); try { const created = await request<{ id: string; topic: string; status: string }>(campaignPath('/video/generate'), jsonRequest('POST', { topic: topic.trim(), style, voice_type: voice || null, template, aspect_ratio: ratio })); setTasks(current => [{ ...created, title: topic.trim() }, ...current]); setActiveId(created.id); setTopic('') } catch (reason) { setError(reason instanceof Error ? reason.message : '视频任务创建失败') } finally { setLoading(false) } }
  async function remove(id: string) { try { await request(campaignPath(`/video/${id}`), jsonRequest('DELETE')); setTasks(current => current.filter(task => task.id !== id)); if (activeId === id) setActiveId('') } catch (reason) { setError(reason instanceof Error ? reason.message : '任务删除失败') } }
  async function download(task: VideoTask) { try { const file = await requestBlob(campaignPath(`/video/download/${task.id}`)); const url = URL.createObjectURL(file.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = file.filename; anchor.click(); URL.revokeObjectURL(url) } catch (reason) { setError(reason instanceof Error ? reason.message : '视频下载失败') } }
  return <section aria-label="短视频生产"><SectionHeading title="脚本、配音与视频渲染" action={<button onClick={() => void load()} className={iconButton} title="刷新任务" aria-label="刷新任务"><RefreshCw size={14} /></button>} /><div className="mt-5 grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-4"><label className="block text-xs text-text-secondary">视频主题<textarea value={topic} onChange={event => setTopic(event.target.value)} className={textareaClass} placeholder="输入商品、知识点或数据故事" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs text-text-secondary">视频模板<select value={template} onChange={event => setTemplate(event.target.value)} className={inputClass}><option value="KnowledgeVideo">干货技能卡</option><option value="DataVizVideo">数据可视化</option></select></label><label className="block text-xs text-text-secondary">画面比例<select value={ratio} onChange={event => setRatio(event.target.value)} className={inputClass}><option>9:16</option><option>16:9</option></select></label><label className="block text-xs text-text-secondary">配音<select value={voice} onChange={event => setVoice(event.target.value)} className={inputClass}>{voices.map(item => <option key={item.value} value={item.value}>{item.label} · {item.gender === 'female' ? '女声' : '男声'}</option>)}</select></label><label className="block text-xs text-text-secondary">脚本风格<input value={style} onChange={event => setStyle(event.target.value)} className={inputClass} /></label></div><div className="flex justify-end gap-2"><button onClick={() => void previewScript()} disabled={!topic.trim() || loading} className={secondaryButton}><Eye size={13} /> 预览脚本</button><button onClick={() => void generate()} disabled={!topic.trim() || loading} className={primaryButton}><Play size={13} /> 生成视频</button></div><ActionState loading={loading} error={error} />{preview && <div className="border-y border-border bg-surface px-4 py-4"><div className="text-xs font-medium text-text">{String(preview.title || '脚本预览')}</div><pre className="mt-3 max-h-80 overflow-y-auto whitespace-pre-wrap font-body text-xs leading-6 text-text-secondary">{JSON.stringify(preview, null, 2)}</pre></div>}</div>
    <aside className="border-y border-border"><div className="border-b border-border px-3 py-3 text-xs text-text-tertiary">渲染任务</div>{tasks.length === 0 ? <div className="py-10 text-center text-xs text-text-tertiary">暂无任务</div> : tasks.map(task => <div key={task.id} className={`grid grid-cols-[minmax(0,1fr)_auto] border-b border-border p-3 last:border-b-0 ${activeId === task.id ? 'bg-surface' : ''}`}><button onClick={() => setActiveId(task.id)} className="min-w-0 text-left"><div className="flex items-center gap-2"><Film size={13} className="shrink-0 text-text-tertiary" /><span className="truncate text-xs text-text">{task.title || task.topic}</span></div><div className={`mt-1 text-[10px] ${task.status === 'completed' ? 'text-success' : task.status === 'failed' ? 'text-danger' : 'text-text-tertiary'}`}>{task.status}</div></button><div className="flex">{task.status === 'completed' && <button onClick={() => void download(task)} className={iconButton} title="下载视频" aria-label="下载视频"><Download size={13} /></button>}<button onClick={() => void remove(task.id)} className={`${iconButton} hover:text-danger`} title="删除任务" aria-label="删除任务"><Trash2 size={13} /></button></div></div>)}</aside></div>
    {activeTask?.error_message && <div className="mt-5"><ActionState error={activeTask.error_message} /></div>}
  </section>
}
